# Twelve-visit longitudinal external-control simulation engine.
#
# Design goals:
#   * last-visit (visit 12) trial-population ATE;
#   * shared covariate coefficients and a linear time term across visits;
#   * mild covariate shift generated by an explicit logistic source model;
#   * subject-level mixture contamination among external controls;
#   * weighted CV-conformal screening based on out-of-fold RCT-control residuals;
#   * longitudinal outcome regressions evaluated at visit 12 inside transported AIPW;
#   * full-pipeline subject bootstrap.

if (!requireNamespace("nlme", quietly = TRUE)) {
  stop("Package 'nlme' is required for the longitudinal simulation.")
}

LONG_T <- 12L
LONG_TIMES <- seq_len(LONG_T)
LONG_XVARS <- c("Y0", "X1", "X2", "B1", "B2", "B3", "B4")
LONG_TRUE_BETA <- c(
  `(Intercept)` = 0,
  Y0 = -0.50,
  X1 = 0.30,
  X2 = -0.30,
  B1 = 0.40,
  B2 = 0.30,
  B3 = 0.25,
  B4 = 0.35,
  time = 0.05
)

long_default_config <- function() {
  list(
    n_r1 = 120L,
    n_r0 = 60L,
    n_ec = 100L,
    T = LONG_T,
    tau = 0.70,
    pi_bad = 0.30,
    sigma2 = 4,
    rho = 0.30,
    bias_intercept = 1.30,
    bias_scale = 2.50,
    bias_time = 0.10,
    outcome_x1 = 0.30,
    gamma = 0.10,
    K = 5L,
    source_strength = "mild"
  )
}

long_score_configs <- function(full = TRUE) {
  core <- list(
    avg = list(shape = "avg", covariance = "internal_cs", weighted = TRUE),
    max = list(shape = "max", covariance = "internal_diag", weighted = TRUE),
    quad = list(shape = "quad", covariance = "internal_diag", weighted = TRUE)
  )
  if (!full) return(core)
  c(core, list(
    final = list(shape = "final", covariance = "internal_cs", weighted = TRUE),
    c1 = list(shape = "c1", covariance = "internal_cs", weighted = TRUE),
    avg_raw = list(shape = "avg", covariance = "raw", weighted = TRUE),
    avg_unweighted = list(shape = "avg", covariance = "internal_cs", weighted = FALSE),
    avg_source = list(shape = "avg", covariance = "source_cs", weighted = TRUE),
    max_source = list(shape = "max", covariance = "source_cs", weighted = TRUE),
    quad_cs = list(shape = "quad", covariance = "internal_cs", weighted = TRUE),
    quad_source = list(shape = "quad", covariance = "source_cs", weighted = TRUE),
    quad_ar1 = list(shape = "quad", covariance = "internal_ar1", weighted = TRUE),
    quad_shrink = list(shape = "quad", covariance = "internal_shrink", weighted = TRUE)
  ))
}

long_working_spec <- function(name = c("CC", "MC", "CM", "MM")) {
  name <- match.arg(name)
  outcome_vars <- LONG_XVARS
  source_vars <- LONG_XVARS
  if (name %in% c("MC", "MM")) outcome_vars <- setdiff(outcome_vars, "X1")
  if (name %in% c("CM", "MM")) source_vars <- setdiff(source_vars, "X1")
  list(name = name, outcome_vars = outcome_vars, source_vars = source_vars)
}

long_cs_matrix <- function(T = LONG_T, sigma2 = 4, rho = 0.30) {
  sigma2 * ((1 - rho) * diag(T) + rho)
}

long_gen_covariates <- function(n) {
  Sx <- outer(seq_len(6), seq_len(6), function(i, j) 0.6 * exp(-0.3 * abs(i - j)))
  latent <- matrix(rnorm(n * 6), n, 6) %*% chol(Sx)
  latent <- sweep(latent, 2, rep(0.3, 6), "+")
  cuts <- c(0, 0.3, -0.2, 0.1)
  B <- vapply(seq_len(4), function(j) as.numeric(latent[, j + 2] > cuts[j]), numeric(n))
  X1 <- latent[, 1]
  X2 <- latent[, 2]
  mu0 <- 0.5 + 0.3 * X1 + 0.2 * X2 + 0.2 * B[, 1] +
    0.15 * B[, 2] + 0.10 * B[, 3] + 0.15 * B[, 4]
  data.frame(
    Y0 = rnorm(n, mu0, 2),
    X1 = X1,
    X2 = X2,
    B1 = B[, 1], B2 = B[, 2], B3 = B[, 3], B4 = B[, 4]
  )
}

long_source_lp <- function(X, target_fraction, strength = "mild") {
  z <- function(x) as.numeric(scale(x))
  cf <- if (identical(strength, "strong_x1")) {
    c(Y0 = -0.15, X1 = 0.30, X2 = -0.10, B1 = 0.15, B2 = -0.10, B3 = 0.08)
  } else {
    c(Y0 = -0.15, X1 = 0.15, X2 = -0.10, B1 = 0.20, B2 = -0.15, B3 = 0.10)
  }
  lp0 <- cf["Y0"] * z(X$Y0) + cf["X1"] * z(X$X1) + cf["X2"] * z(X$X2) +
    cf["B1"] * (X$B1 - mean(X$B1)) + cf["B2"] * (X$B2 - mean(X$B2)) +
    cf["B3"] * (X$B3 - mean(X$B3))
  alpha <- uniroot(function(a) mean(plogis(a + lp0)) - target_fraction, c(-8, 8))$root
  list(lp = alpha + lp0, alpha = alpha)
}

long_control_mean <- function(X, config = long_default_config()) {
  -0.50 * X$Y0 + config$outcome_x1 * X$X1 - 0.30 * X$X2 + 0.40 * X$B1 +
    0.30 * X$B2 + 0.25 * X$B3 + 0.35 * X$B4
}

long_bias_matrix <- function(X, config) {
  h <- config$bias_intercept + 0.30 * X$Y0 + 0.25 * X$X1 + 0.25 * X$X2 +
    0.30 * X$B1 + 0.20 * X$B2 + 0.15 * X$B3 + 0.25 * X$B4
  outer(config$bias_scale * h, rep(1, config$T)) +
    outer(rep(1, nrow(X)), config$bias_time * seq_len(config$T))
}

long_noise <- function(n, config) {
  Sigma <- long_cs_matrix(config$T, config$sigma2, config$rho)
  matrix(rnorm(n * config$T), n, config$T) %*% chol(Sigma)
}

long_generate_data <- function(config = long_default_config(), pool_mult = 30L) {
  n_r <- config$n_r1 + config$n_r0
  n_pool <- as.integer(pool_mult * (n_r + config$n_ec))
  Xpool <- long_gen_covariates(n_pool)
  slp <- long_source_lp(Xpool, n_r / (n_r + config$n_ec), config$source_strength)
  ps <- plogis(slp$lp)

  idx_r <- sample.int(n_pool, n_r, replace = FALSE, prob = ps)
  remain <- setdiff(seq_len(n_pool), idx_r)
  idx_e <- sample(remain, config$n_ec, replace = FALSE, prob = 1 - ps[remain])
  Xr <- Xpool[idx_r, , drop = FALSE]
  Xe <- Xpool[idx_e, , drop = FALSE]
  rownames(Xr) <- rownames(Xe) <- NULL

  A <- integer(n_r)
  A[sample.int(n_r, config$n_r1)] <- 1L
  base_r <- long_control_mean(Xr, config)
  mu_r <- outer(base_r, rep(1, config$T)) +
    outer(rep(1, n_r), 0.05 * seq_len(config$T)) +
    outer(A * config$tau, rep(1, config$T))
  Yr <- mu_r + long_noise(n_r, config)

  base_e <- long_control_mean(Xe, config)
  mu_e <- outer(base_e, rep(1, config$T)) + outer(rep(1, config$n_ec), 0.05 * seq_len(config$T))
  bad <- rbinom(config$n_ec, 1, config$pi_bad)
  bias <- long_bias_matrix(Xe, config)
  Ye <- mu_e - bad * bias + long_noise(config$n_ec, config)

  list(
    Yt = Yr[A == 1, , drop = FALSE], Xt = Xr[A == 1, , drop = FALSE],
    Yc = Yr[A == 0, , drop = FALSE], Xc = Xr[A == 0, , drop = FALSE],
    Ye = Ye, Xe = Xe, B = bad, bias = bias,
    config = config,
    source_alpha = slp$alpha,
    source_prob_quantiles = unname(quantile(ps, c(0.01, 0.5, 0.99)))
  )
}

long_set_null <- function(dat) {
  out <- dat
  out$Yt <- dat$Yt - dat$config$tau
  out$config$tau <- 0
  out
}

long_to_long <- function(Y, X) {
  n <- nrow(Y)
  T <- ncol(Y)
  data.frame(
    id = factor(rep(seq_len(n), each = T)),
    time = rep(seq_len(T), n),
    Y = as.vector(t(Y)),
    X[rep(seq_len(n), each = T), , drop = FALSE],
    row.names = NULL
  )
}

long_cov_moment <- function(resid, kind = c("cs", "diag", "ar1", "shrink"), ridge = 1e-6) {
  kind <- match.arg(kind)
  T <- ncol(resid)
  S <- stats::cov(resid)
  if (any(!is.finite(S))) S <- diag(rep(stats::var(as.numeric(resid), na.rm = TRUE), T))
  S <- S + ridge * diag(T)
  if (kind == "diag") return(diag(pmax(diag(S), ridge), T))
  if (kind == "shrink") return(0.75 * S + 0.25 * diag(diag(S), T))
  sigma2 <- mean(diag(S))
  if (kind == "cs") {
    rho <- mean(S[row(S) != col(S)]) / sigma2
    rho <- min(0.98, max(-1 / (T - 1) + 1e-4, rho))
    return(long_cs_matrix(T, sigma2, rho))
  }
  lag1 <- mean(S[cbind(seq_len(T - 1), 2:T)])
  rho <- min(0.98, max(-0.98, lag1 / sigma2))
  sigma2 * outer(seq_len(T), seq_len(T), function(i, j) rho^abs(i - j))
}

long_fit_outcome <- function(Y, X, vars = LONG_XVARS, longitudinal = TRUE) {
  if (longitudinal) {
    dat <- long_to_long(Y, X)
    form <- reformulate(c(vars, "time"), response = "Y")
    # do.call embeds the actual formula in the stored gls call. Passing a local
    # symbol such as model = form makes predict.gls later search for a vanished
    # object named `form`.
    fit <- try(do.call(nlme::gls, list(
      model = form,
      correlation = nlme::corCompSymm(form = ~ 1 | id),
      data = dat,
      method = "REML",
      control = nlme::glsControl(msMaxIter = 100, returnObject = TRUE)
    )), silent = TRUE)
    fallback <- inherits(fit, "try-error")
    if (fallback) fit <- lm(form, data = dat)
    pred_matrix <- function(newX, times = seq_len(ncol(Y))) {
      nd <- data.frame(
        id = factor(rep(seq_len(nrow(newX)), each = length(times))),
        time = rep(times, nrow(newX)),
        newX[rep(seq_len(nrow(newX)), each = length(times)), , drop = FALSE],
        row.names = NULL
      )
      matrix(as.numeric(predict(fit, newdata = nd)), nrow(newX), length(times), byrow = TRUE)
    }
    fitted_train <- pred_matrix(X, seq_len(ncol(Y)))
    resid <- Y - fitted_train
    if (!fallback) {
      sigma2 <- fit$sigma^2
      rho <- unname(coef(fit$modelStruct$corStruct, unconstrained = FALSE))[1]
      Sigma <- long_cs_matrix(ncol(Y), sigma2, rho)
    } else {
      Sigma <- long_cov_moment(resid, "cs")
      sigma2 <- mean(diag(Sigma))
      rho <- mean(Sigma[row(Sigma) != col(Sigma)]) / sigma2
    }
    return(list(
      fit = fit, predict_matrix = pred_matrix, residuals = resid,
      Sigma = Sigma, sigma2 = sigma2, rho = rho,
      coefficients = coef(fit), fallback = fallback, longitudinal = TRUE
    ))
  }

  df <- cbind(X, Y = Y[, ncol(Y)])
  form <- reformulate(vars, response = "Y")
  fit <- lm(form, data = df)
  pred_matrix <- function(newX, times = ncol(Y)) {
    matrix(as.numeric(predict(fit, newdata = newX)), nrow(newX), length(times))
  }
  list(
    fit = fit, predict_matrix = pred_matrix,
    residuals = matrix(residuals(fit), ncol = 1), Sigma = matrix(summary(fit)$sigma^2, 1, 1),
    sigma2 = summary(fit)$sigma^2, rho = NA_real_, coefficients = coef(fit),
    fallback = FALSE, longitudinal = FALSE
  )
}

long_predict_at <- function(fit, X, time = LONG_T) {
  as.numeric(fit$predict_matrix(X, time)[, 1])
}

long_fit_source <- function(Xr, Xe, vars = LONG_XVARS) {
  Xall <- rbind(Xr, Xe)
  D <- model.matrix(reformulate(vars), data = Xall)
  y <- c(rep(1, nrow(Xr)), rep(0, nrow(Xe)))
  fit <- suppressWarnings(glm.fit(D, y, family = binomial()))
  cf <- fit$coefficients
  cf[!is.finite(cf)] <- 0
  list(
    coefficients = cf,
    vars = vars,
    nR = nrow(Xr), nE = nrow(Xe),
    omega = function(newX) {
      eta <- as.numeric(model.matrix(reformulate(vars), data = newX) %*% cf)
      w <- exp(pmin(12, pmax(-12, -eta))) * (nrow(Xr) / nrow(Xe))
      pmin(20, pmax(0.05, w))
    },
    rho = function(newX) {
      eta <- as.numeric(model.matrix(reformulate(vars), data = newX) %*% cf)
      w <- exp(pmin(12, pmax(-12, eta))) * (nrow(Xe) / nrow(Xr))
      pmin(20, pmax(0.05, w))
    },
    converged = isTRUE(fit$converged)
  )
}

long_safe_inverse <- function(S) {
  S <- (S + t(S)) / 2
  for (ridge in c(0, 1e-8, 1e-6, 1e-4, 1e-2)) {
    z <- try(chol2inv(chol(S + ridge * mean(diag(S)) * diag(nrow(S)))), silent = TRUE)
    if (!inherits(z, "try-error")) return(z)
  }
  solve(diag(pmax(diag(S), 1e-6)))
}

long_score <- function(resid, Sigma, shape = c("avg", "final", "c1", "max", "quad")) {
  shape <- match.arg(shape)
  T <- ncol(resid)
  if (shape == "max") {
    return(apply(sweep(abs(resid), 2, sqrt(pmax(diag(Sigma), 1e-8)), "/"), 1, max))
  }
  if (shape == "quad") {
    Sinv <- long_safe_inverse(Sigma)
    return(rowSums((resid %*% Sinv) * resid))
  }
  cc <- switch(shape,
    avg = rep(1 / T, T),
    final = c(rep(0, T - 1), 1),
    c1 = c(-1, rep(0, T - 2), 1)
  )
  abs(as.numeric(resid %*% cc)) / sqrt(as.numeric(crossprod(cc, Sigma %*% cc)))
}

long_sigma_for <- function(kind, fit_r, resid_r, resid_e) {
  T <- ncol(resid_r)
  switch(kind,
    raw = diag(T),
    internal_cs = fit_r$Sigma,
    internal_diag = diag(diag(fit_r$Sigma), T),
    internal_ar1 = {
      r <- min(0.95, max(-0.95, fit_r$rho))
      fit_r$sigma2 * outer(seq_len(T), seq_len(T), function(i, j) r^abs(i - j))
    },
    internal_shrink = long_cov_moment(resid_r, "shrink"),
    source_cs = long_cov_moment(resid_e, "cs"),
    source_shrink = long_cov_moment(resid_e, "shrink"),
    stop("Unknown covariance treatment: ", kind)
  )
}

long_screen_cv <- function(dat, spec = long_working_spec("CC"),
                           score_configs = long_score_configs(TRUE), gamma = 0.10, K = 5L) {
  n <- nrow(dat$Yc)
  K <- min(as.integer(K), n)
  fold <- sample(rep(seq_len(K), length.out = n))
  Xr <- rbind(dat$Xt, dat$Xc)
  src <- long_fit_source(Xr, dat$Xe, spec$source_vars)
  wc <- src$omega(dat$Xc)
  we <- src$omega(dat$Xe)

  vcal <- setNames(lapply(score_configs, function(x) numeric(n)), names(score_configs))
  vec <- setNames(lapply(score_configs, function(x) matrix(NA_real_, nrow(dat$Ye), K)), names(score_configs))
  fold_fallback <- logical(K)
  fold_sigma2 <- fold_rho <- numeric(K)

  for (k in seq_len(K)) {
    itr <- which(fold != k)
    ical <- which(fold == k)
    fit <- long_fit_outcome(dat$Yc[itr, , drop = FALSE], dat$Xc[itr, , drop = FALSE],
                            spec$outcome_vars, longitudinal = TRUE)
    fold_fallback[k] <- fit$fallback
    fold_sigma2[k] <- fit$sigma2
    fold_rho[k] <- fit$rho
    rr <- dat$Yc[ical, , drop = FALSE] - fit$predict_matrix(dat$Xc[ical, , drop = FALSE])
    re <- dat$Ye - fit$predict_matrix(dat$Xe)
    rtrain <- fit$residuals
    for (nm in names(score_configs)) {
      sc <- score_configs[[nm]]
      Sr <- long_sigma_for(sc$covariance, fit, rtrain, re)
      Se <- if (startsWith(sc$covariance, "source_")) Sr else Sr
      # For source-specific scores, calibration uses the internal covariance and EC uses source covariance.
      if (startsWith(sc$covariance, "source_")) {
        Sr <- fit$Sigma
        if (sc$covariance == "source_shrink") Se <- long_cov_moment(re, "shrink")
      }
      vcal[[nm]][ical] <- long_score(rr, Sr, sc$shape)
      vec[[nm]][, k] <- long_score(re, Se, sc$shape)
    }
  }

  pvals <- selections <- list()
  for (nm in names(score_configs)) {
    sc <- score_configs[[nm]]
    wcal <- if (isTRUE(sc$weighted)) wc else rep(1, n)
    wtest <- if (isTRUE(sc$weighted)) we else rep(1, nrow(dat$Ye))
    num <- wtest
    for (k in seq_len(K)) {
      ik <- which(fold == k)
      cmp <- outer(vec[[nm]][, k], vcal[[nm]][ik], function(a, b) b >= a)
      num <- num + as.numeric(cmp %*% wcal[ik])
    }
    pvals[[nm]] <- num / (wtest + sum(wcal))
    selections[[nm]] <- pvals[[nm]] > gamma
  }

  list(
    p = pvals, selected = selections, fold = fold,
    source_fit = src, source_weights_rct = wc, source_weights_ec = we,
    sigma2 = mean(fold_sigma2), rho = mean(fold_rho),
    fallback_rate = mean(fold_fallback)
  )
}

long_aipw_rct_means <- function(dat, spec, longitudinal = TRUE) {
  Xr <- rbind(dat$Xt, dat$Xc)
  fit1 <- long_fit_outcome(dat$Yt, dat$Xt, spec$outcome_vars, longitudinal)
  fit0 <- long_fit_outcome(dat$Yc, dat$Xc, spec$outcome_vars, longitudinal)
  target_time <- ncol(dat$Yc)
  p1_all <- long_predict_at(fit1, Xr, target_time)
  p0_all <- long_predict_at(fit0, Xr, target_time)
  p1_obs <- long_predict_at(fit1, dat$Xt, target_time)
  p0_obs <- long_predict_at(fit0, dat$Xc, target_time)
  r1 <- dat$Yt[, target_time] - p1_obs
  r0 <- dat$Yc[, target_time] - p0_obs
  mu1 <- mean(p1_all) + mean(r1)
  mu0 <- mean(p0_all) + mean(r0)

  n1 <- nrow(dat$Yt)
  n0 <- nrow(dat$Yc)
  nr <- n1 + n0
  e1 <- n1 / nr
  e0 <- n0 / nr
  A <- c(rep(1, n1), rep(0, n0))
  residual1 <- c(r1, rep(0, n0))
  residual0 <- c(rep(0, n1), r0)
  if1 <- p1_all - mean(p1_all) + A / e1 * residual1
  if0 <- p0_all - mean(p0_all) + (1 - A) / e0 * residual0
  list(
    mu1 = mu1, mu0 = mu0,
    v1 = var(if1) / nr, v0 = var(if0) / nr,
    fit1 = fit1, fit0 = fit0,
    p1_all = p1_all, p0_all = p0_all,
    residual1 = r1, residual0 = r0
  )
}

long_external_control <- function(dat, sel, spec, target_pred_var = 0) {
  ret <- which(sel)
  Xr <- rbind(dat$Xt, dat$Xc)
  if (length(ret) < max(10L, length(spec$outcome_vars) + 3L)) {
    return(list(ok = FALSE, mu0 = NA_real_, variance = Inf, ess = 0, n = length(ret),
                fit = NULL, source_fit = NULL, mean_weight = NA_real_, max_weight = NA_real_))
  }
  Xe <- dat$Xe[ret, , drop = FALSE]
  Ye <- dat$Ye[ret, , drop = FALSE]
  fit <- long_fit_outcome(Ye, Xe, spec$outcome_vars, longitudinal = TRUE)
  target_time <- ncol(dat$Ye)
  p_target <- long_predict_at(fit, Xr, target_time)
  p_ext <- long_predict_at(fit, Xe, target_time)
  src <- long_fit_source(Xr, Xe, spec$source_vars)
  w <- src$rho(Xe)
  # Mild overlap is part of the design. A deterministic cap avoids a single estimated
  # propensity dominating a small retained sample while preserving the density-ratio direction.
  cap <- min(20, unname(quantile(w, 0.99, na.rm = TRUE)))
  w <- pmin(w, cap)
  resid <- Ye[, target_time] - p_ext
  aug <- sum(w * resid) / sum(w)
  mu0 <- mean(p_target) + aug
  wn <- w / sum(w)
  ess <- sum(w)^2 / sum(w^2)
  v_target <- var(p_target) / nrow(Xr)
  v_resid <- sum(wn^2 * (resid - aug)^2)
  list(
    ok = TRUE, mu0 = mu0, variance = v_target + v_resid,
    ess = ess, n = length(ret), fit = fit, source_fit = src,
    mean_weight = mean(w), max_weight = max(w), residual_mean = aug
  )
}

long_estimate_methods <- function(dat, screen, spec = long_working_spec("CC"),
                                  inference_scores = c("avg", "max", "quad")) {
  rct_long <- long_aipw_rct_means(dat, spec, longitudinal = TRUE)
  rct_final <- long_aipw_rct_means(dat, spec, longitudinal = FALSE)
  out <- c(
    rct_final = rct_final$mu1 - rct_final$mu0,
    rct_long = rct_long$mu1 - rct_long$mu0
  )
  aux <- list(
    rct_final = list(lambda = 0, ess = 0, retained = 0),
    rct_long = list(lambda = 0, ess = 0, retained = 0)
  )

  selections <- list(full = rep(TRUE, nrow(dat$Ye)), oracle = dat$B == 0)
  for (nm in inference_scores) selections[[nm]] <- screen$selected[[nm]]
  for (nm in names(selections)) {
    ext <- long_external_control(dat, selections[[nm]], spec)
    if (!ext$ok || !is.finite(ext$variance)) {
      lambda <- 0
      tau <- rct_long$mu1 - rct_long$mu0
    } else {
      lambda <- rct_long$v0 / (rct_long$v0 + ext$variance)
      lambda <- min(0.95, max(0, lambda))
      mu0 <- (1 - lambda) * rct_long$mu0 + lambda * ext$mu0
      tau <- rct_long$mu1 - mu0
    }
    out[nm] <- tau
    aux[[nm]] <- list(
      lambda = lambda, ess = ext$ess, retained = ext$n,
      external_mu0 = ext$mu0, external_variance = ext$variance,
      max_weight = ext$max_weight,
      fallback = if (is.null(ext$fit)) NA_real_ else as.numeric(ext$fit$fallback)
    )
  }

  cf <- rct_long$fit0$coefficients
  nuisance <- c(
    setNames(cf[intersect(names(cf), names(LONG_TRUE_BETA))],
             paste0("beta_", intersect(names(cf), names(LONG_TRUE_BETA)))),
    sigma2 = rct_long$fit0$sigma2,
    rho = rct_long$fit0$rho,
    outcome_fallback = as.numeric(rct_long$fit0$fallback),
    source_converged = as.numeric(screen$source_fit$converged),
    screen_fallback = screen$fallback_rate
  )
  list(estimates = out, aux = aux, nuisance = nuisance)
}

long_screen_metrics <- function(dat, screen) {
  out <- lapply(names(screen$selected), function(nm) {
    keep <- screen$selected[[nm]]
    bad <- dat$B == 1
    data.frame(
      score = nm,
      detection = if (any(bad)) mean(!keep[bad]) else NA_real_,
      wrong_detection = if (any(!bad)) mean(!keep[!bad]) else NA_real_,
      retained_clean = sum(keep & !bad),
      retained_bad = sum(keep & bad),
      retained_bad_fraction = if (sum(keep) > 0) mean(bad[keep]) else NA_real_,
      mean_p_clean = if (any(!bad)) mean(screen$p[[nm]][!bad]) else NA_real_,
      mean_p_bad = if (any(bad)) mean(screen$p[[nm]][bad]) else NA_real_
    )
  })
  do.call(rbind, out)
}

long_resample_data <- function(dat) {
  it <- sample.int(nrow(dat$Yt), nrow(dat$Yt), replace = TRUE)
  ic <- sample.int(nrow(dat$Yc), nrow(dat$Yc), replace = TRUE)
  ie <- sample.int(nrow(dat$Ye), nrow(dat$Ye), replace = TRUE)
  list(
    Yt = dat$Yt[it, , drop = FALSE], Xt = dat$Xt[it, , drop = FALSE],
    Yc = dat$Yc[ic, , drop = FALSE], Xc = dat$Xc[ic, , drop = FALSE],
    Ye = dat$Ye[ie, , drop = FALSE], Xe = dat$Xe[ie, , drop = FALSE],
    B = dat$B[ie], bias = dat$bias[ie, , drop = FALSE],
    config = dat$config,
    source_alpha = dat$source_alpha,
    source_prob_quantiles = dat$source_prob_quantiles
  )
}

long_run_dataset <- function(dat, spec = long_working_spec("CC"), Bboot = 0L,
                             score_configs = long_score_configs(TRUE),
                             inference_scores = c("avg", "max", "quad"),
                             seed = NULL, keep_boot = FALSE) {
  if (!is.null(seed)) set.seed(seed)
  screen <- long_screen_cv(dat, spec, score_configs, dat$config$gamma, dat$config$K)
  point <- long_estimate_methods(dat, screen, spec, inference_scores)
  sm <- long_screen_metrics(dat, screen)
  methods <- names(point$estimates)
  boot <- matrix(NA_real_, nrow = Bboot, ncol = length(methods), dimnames = list(NULL, methods))
  if (Bboot > 0) {
    for (b in seq_len(Bboot)) {
      db <- long_resample_data(dat)
      sb <- try(long_screen_cv(db, spec, score_configs, db$config$gamma, db$config$K), silent = TRUE)
      if (inherits(sb, "try-error")) next
      eb <- try(long_estimate_methods(db, sb, spec, inference_scores)$estimates, silent = TRUE)
      if (!inherits(eb, "try-error")) boot[b, names(eb)] <- eb
    }
  }
  valid_boot <- if (Bboot > 0) colMeans(is.finite(boot)) else setNames(rep(NA_real_, length(methods)), methods)
  ci <- se <- setNames(rep(NA_real_, length(methods)), methods)
  if (Bboot > 0) {
    for (m in methods) {
      z <- boot[, m]
      z <- z[is.finite(z)]
      if (length(z) >= max(20, 0.8 * Bboot)) {
        ci[m] <- NA_real_ # placeholder keeps named vector shape; matrix is built below
        se[m] <- sd(z)
      }
    }
  }
  ci_mat <- matrix(NA_real_, length(methods), 2, dimnames = list(methods, c("lower", "upper")))
  if (Bboot > 0) {
    for (m in methods) {
      z <- boot[, m]
      z <- z[is.finite(z)]
      if (length(z) >= max(20, 0.8 * Bboot)) ci_mat[m, ] <- quantile(z, c(0.025, 0.975), names = FALSE)
    }
  }
  list(
    estimates = point$estimates, aux = point$aux, nuisance = point$nuisance,
    screen_metrics = sm, ci = ci_mat, boot_se = se, boot_valid = valid_boot,
    boot = if (keep_boot) boot else NULL
  )
}

long_one_rep <- function(rep_id, config = long_default_config(), spec = long_working_spec("CC"),
                         Bboot = 0L, score_configs = long_score_configs(TRUE),
                         inference_scores = c("avg", "max", "quad"),
                         base_seed = 20260717L, keep_boot = FALSE) {
  set.seed(base_seed + rep_id)
  dat_alt <- long_generate_data(config)
  dat <- long_set_null(dat_alt)
  ans <- long_run_dataset(
    dat, spec, Bboot = Bboot, score_configs = score_configs,
    inference_scores = inference_scores, seed = base_seed + 100000L + rep_id,
    keep_boot = keep_boot
  )
  # The treatment effect is an additive constant at every visit. Therefore every
  # longitudinal and final outcome model with an intercept shifts exactly by tau;
  # null and alternative bootstrap distributions differ only by this constant.
  ans$estimates_alt <- ans$estimates + config$tau
  ans$ci_alt <- ans$ci + config$tau
  ans$rep_id <- rep_id
  ans$config <- config
  ans$spec <- spec$name
  ans
}

long_summarize <- function(results, tau, spec_name = "CC", config = long_default_config()) {
  ok <- vapply(results, function(x) is.list(x) && !inherits(x, "try-error"), logical(1))
  results <- results[ok]
  if (!length(results)) stop("No valid simulation replications.")
  safe_mean <- function(z) if (any(is.finite(z))) mean(z, na.rm = TRUE) else NA_real_
  methods <- names(results[[1]]$estimates)
  est0 <- t(vapply(results, function(x) x$estimates[methods], numeric(length(methods))))
  est1 <- t(vapply(results, function(x) x$estimates_alt[methods], numeric(length(methods))))
  ses <- t(vapply(results, function(x) x$boot_se[methods], numeric(length(methods))))
  lower0 <- t(vapply(results, function(x) x$ci[methods, "lower"], numeric(length(methods))))
  upper0 <- t(vapply(results, function(x) x$ci[methods, "upper"], numeric(length(methods))))
  lower1 <- t(vapply(results, function(x) x$ci_alt[methods, "lower"], numeric(length(methods))))
  upper1 <- t(vapply(results, function(x) x$ci_alt[methods, "upper"], numeric(length(methods))))

  estimation <- do.call(rbind, lapply(seq_along(methods), function(j) {
    m <- methods[j]
    empirical_sd <- sd(est1[, j], na.rm = TRUE)
    bias <- mean(est1[, j], na.rm = TRUE) - tau
    mse <- mean((est1[, j] - tau)^2, na.rm = TRUE)
    data.frame(
      spec = spec_name, method = m, n_rep = sum(is.finite(est1[, j])),
      mean = mean(est1[, j], na.rm = TRUE), bias = bias,
      empirical_sd = empirical_sd, variance = var(est1[, j], na.rm = TRUE),
      mse = mse, rmse = sqrt(mse), bias_squared = bias^2,
      mean_boot_se = safe_mean(ses[, j]),
      se_sd_ratio = safe_mean(ses[, j]) / empirical_sd,
      coverage = safe_mean(as.numeric(lower1[, j] <= tau & upper1[, j] >= tau)),
      type1 = safe_mean(as.numeric(lower0[, j] > 0 | upper0[, j] < 0)),
      power = safe_mean(as.numeric(lower1[, j] > 0 | upper1[, j] < 0)),
      mean_ci_length = safe_mean(upper1[, j] - lower1[, j])
    )
  }))

  screen <- do.call(rbind, lapply(results, function(x) x$screen_metrics))
  screen_fields <- c(
    "detection", "wrong_detection", "retained_clean", "retained_bad",
    "retained_bad_fraction", "mean_p_clean", "mean_p_bad"
  )
  screen_summary <- do.call(rbind, lapply(split(screen, screen$score), function(d) {
    data.frame(
      score = d$score[1],
      as.list(vapply(d[screen_fields], safe_mean, numeric(1))),
      row.names = NULL, check.names = FALSE
    )
  }))
  screen_summary$spec <- spec_name

  aux_methods <- setdiff(methods, c("rct_final", "rct_long"))
  borrowing <- do.call(rbind, lapply(aux_methods, function(m) {
    vals <- lapply(results, function(x) x$aux[[m]])
    data.frame(
      spec = spec_name, method = m,
      mean_lambda = mean(vapply(vals, function(z) z$lambda, numeric(1)), na.rm = TRUE),
      mean_ess = mean(vapply(vals, function(z) z$ess, numeric(1)), na.rm = TRUE),
      mean_retained = mean(vapply(vals, function(z) z$retained, numeric(1)), na.rm = TRUE),
      mean_max_weight = mean(vapply(vals, function(z) z$max_weight, numeric(1)), na.rm = TRUE)
    )
  }))

  nuis_names <- unique(unlist(lapply(results, function(x) names(x$nuisance))))
  nuisance <- do.call(rbind, lapply(nuis_names, function(nm) {
    v <- vapply(results, function(x) if (nm %in% names(x$nuisance)) x$nuisance[[nm]] else NA_real_, numeric(1))
    truth_name <- sub("^beta_", "", nm)
    truth <- if (nm == "beta_X1") config$outcome_x1 else
      if (truth_name %in% names(LONG_TRUE_BETA)) LONG_TRUE_BETA[[truth_name]] else
      if (nm == "sigma2") config$sigma2 else if (nm == "rho") config$rho else NA_real_
    data.frame(
      spec = spec_name, parameter = nm, truth = truth,
      mean = mean(v, na.rm = TRUE), bias = if (is.finite(truth)) mean(v, na.rm = TRUE) - truth else NA_real_,
      rmse = if (is.finite(truth)) sqrt(mean((v - truth)^2, na.rm = TRUE)) else NA_real_,
      sd = sd(v, na.rm = TRUE)
    )
  }))

  list(estimation = estimation, screening = screen_summary, borrowing = borrowing,
       nuisance = nuisance, n_valid = length(results))
}
